version: "2"
linters:
  default: all
  disable:
    - bodyclose
    - depguard
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - ireturn
    - mnd
    - nakedret
    - nilnil
    - nonamedreturns
    - paralleltest
    - revive
    - tagalign
    - tagliatelle
    - wrapcheck
  settings:
    lll:
      line-length: 180
    varnamelen:
      ignore-names:
        - k
        - v
        - w
        - i
        - r
        - fn
        - ok
        - lc
        - db
        - id
        - os
        - md
        - fs
        - sh
        - ua
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - tmp
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - tmp
      - third_party$
      - builtin$
      - examples$
