version: "2"
linters:
  settings:
    gosec:
      excludes:
        - G117
    lll:
      line-length: 180
  default: all
  disable:
    - bodyclose
    - depguard
    - embeddedstructfieldcheck
    - err113
    - exhaustruct
    - forcetypeassert
    - funcorder
    - gochecknoglobals
    - gochecknoinits
    - ireturn
    - mnd
    - nakedret
    - nilnil
    - nlreturn
    - nonamedreturns
    - noinlineerr
    - paralleltest
    - revive
    - tagalign
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - tmp
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - tmp
      - third_party$
      - builtin$
      - examples$
