issues:
  exclude-dirs:
    - tmp
linters-settings:
  lll:
    line-length: 180
linters:
  enable-all: true
  disable:
    - exportloopref
    - execinquery
    - gomnd
    - errcheck
    - tagalign
    - gochecknoinits
    - bodyclose
    - canonicalheader
    - depguard
    - err113
    - exhaustruct
    - fatcontext
    - forcetypeassert
    - gochecknoglobals
    - ireturn
    - mnd
    - paralleltest
    - varnamelen
    - wrapcheck
    - tagliatelle
    - usestdlibvars
    - intrange
