package health

import (
	health "github.com/alexfalkowski/go-health/v2/server"
	"github.com/alexfalkowski/go-service/v2/di"
	"github.com/alexfalkowski/go-service/v2/env"
	"github.com/alexfalkowski/go-service/v2/net/http"
	"github.com/alexfalkowski/go-service/v2/net/http/status"
)

// RegisterParams defines dependencies for registering HTTP health endpoints.
//
// It is an Fx parameter struct (`di.In`) used to wire standard Kubernetes-style health endpoints:
//
//   - `/healthz` (general health)
//   - `/livez` (liveness)
//   - `/readyz` (readiness)
//
// Server and Mux are required. Register assumes both are already constructed by the surrounding Fx graph.
type RegisterParams struct {
	di.In

	// Server stores the named health observers queried by the HTTP handlers.
	Server *health.Server

	// Mux is the HTTP serve mux the health handlers are registered on.
	Mux *http.ServeMux

	// Name is the service name used both for route prefixing and observer lookup.
	Name env.Name
}

// Register registers the standard HTTP health endpoints.
//
// It registers GET handlers for `/healthz`, `/livez`, and `/readyz` using the service-prefixed
// route generated by http.Pattern(params.Name, <path>).
//
// Each handler resolves the corresponding observer on params.Server by stripping the leading slash
// from the route name and looking it up under params.Name. The handler then returns:
//
//   - HTTP 200 with the plain-text body "SERVING" when the observer reports no error.
//   - HTTP 503 when the observer is missing or reports an error.
//
// Error responses are written with status.WriteError, and successful responses are written with
// status.WriteText. Callers are expected to have request metadata middleware in place if they want
// request-scoped metadata populated on the handler context.
func Register(params RegisterParams) {
	resister("/healthz", params)
	resister("/livez", params)
	resister("/readyz", params)
}

func resister(pattern string, params RegisterParams) {
	params.Mux.HandleFunc("GET "+http.Pattern(params.Name, pattern), func(res http.ResponseWriter, req *http.Request) {
		observer, err := params.Server.Observer(params.Name.String(), pattern[1:])
		if err != nil {
			status.WriteError(req.Context(), res, status.ServiceUnavailableError(err))
			return
		}
		if err := observer.Error(); err != nil {
			status.WriteError(req.Context(), res, status.ServiceUnavailableError(err))
			return
		}

		status.WriteText(req.Context(), res, "SERVING")
	})
}
