// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: greet/v1/partial.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PartialMessage is a proto2 fixture with a required field, used to exercise
// codec.WithAllowPartial on proto Encode.
type PartialMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartialMessage) Reset() {
	*x = PartialMessage{}
	mi := &file_greet_v1_partial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialMessage) ProtoMessage() {}

func (x *PartialMessage) ProtoReflect() protoreflect.Message {
	mi := &file_greet_v1_partial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialMessage.ProtoReflect.Descriptor instead.
func (*PartialMessage) Descriptor() ([]byte, []int) {
	return file_greet_v1_partial_proto_rawDescGZIP(), []int{0}
}

func (x *PartialMessage) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_greet_v1_partial_proto protoreflect.FileDescriptor

const file_greet_v1_partial_proto_rawDesc = "" +
	"\n" +
	"\x16greet/v1/partial.proto\x12\bgreet.v1\"$\n" +
	"\x0ePartialMessage\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04nameB6Z4github.com/alexfalkowski/go-service/v2/test/greet/v1"

var (
	file_greet_v1_partial_proto_rawDescOnce sync.Once
	file_greet_v1_partial_proto_rawDescData []byte
)

func file_greet_v1_partial_proto_rawDescGZIP() []byte {
	file_greet_v1_partial_proto_rawDescOnce.Do(func() {
		file_greet_v1_partial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greet_v1_partial_proto_rawDesc), len(file_greet_v1_partial_proto_rawDesc)))
	})
	return file_greet_v1_partial_proto_rawDescData
}

var file_greet_v1_partial_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_greet_v1_partial_proto_goTypes = []any{
	(*PartialMessage)(nil), // 0: greet.v1.PartialMessage
}
var file_greet_v1_partial_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_greet_v1_partial_proto_init() }
func file_greet_v1_partial_proto_init() {
	if File_greet_v1_partial_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greet_v1_partial_proto_rawDesc), len(file_greet_v1_partial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_greet_v1_partial_proto_goTypes,
		DependencyIndexes: file_greet_v1_partial_proto_depIdxs,
		MessageInfos:      file_greet_v1_partial_proto_msgTypes,
	}.Build()
	File_greet_v1_partial_proto = out.File
	file_greet_v1_partial_proto_goTypes = nil
	file_greet_v1_partial_proto_depIdxs = nil
}
