// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: greet/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_greet_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_greet_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_greet_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_greet_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SayStreamHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayStreamHelloRequest) Reset() {
	*x = SayStreamHelloRequest{}
	mi := &file_greet_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayStreamHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayStreamHelloRequest) ProtoMessage() {}

func (x *SayStreamHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayStreamHelloRequest.ProtoReflect.Descriptor instead.
func (*SayStreamHelloRequest) Descriptor() ([]byte, []int) {
	return file_greet_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *SayStreamHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayStreamHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayStreamHelloResponse) Reset() {
	*x = SayStreamHelloResponse{}
	mi := &file_greet_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayStreamHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayStreamHelloResponse) ProtoMessage() {}

func (x *SayStreamHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayStreamHelloResponse.ProtoReflect.Descriptor instead.
func (*SayStreamHelloResponse) Descriptor() ([]byte, []int) {
	return file_greet_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *SayStreamHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_greet_v1_service_proto protoreflect.FileDescriptor

const file_greet_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x16greet/v1/service.proto\x12\bgreet.v1\"%\n" +
	"\x0fSayHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"+\n" +
	"\x15SayStreamHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"2\n" +
	"\x16SayStreamHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb0\x01\n" +
	"\x0eGreeterService\x12C\n" +
	"\bSayHello\x12\x19.greet.v1.SayHelloRequest\x1a\x1a.greet.v1.SayHelloResponse\"\x00\x12Y\n" +
	"\x0eSayStreamHello\x12\x1f.greet.v1.SayStreamHelloRequest\x1a .greet.v1.SayStreamHelloResponse\"\x00(\x010\x01B6Z4github.com/alexfalkowski/go-service/v2/test/greet/v1b\x06proto3"

var (
	file_greet_v1_service_proto_rawDescOnce sync.Once
	file_greet_v1_service_proto_rawDescData []byte
)

func file_greet_v1_service_proto_rawDescGZIP() []byte {
	file_greet_v1_service_proto_rawDescOnce.Do(func() {
		file_greet_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greet_v1_service_proto_rawDesc), len(file_greet_v1_service_proto_rawDesc)))
	})
	return file_greet_v1_service_proto_rawDescData
}

var file_greet_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_greet_v1_service_proto_goTypes = []any{
	(*SayHelloRequest)(nil),        // 0: greet.v1.SayHelloRequest
	(*SayHelloResponse)(nil),       // 1: greet.v1.SayHelloResponse
	(*SayStreamHelloRequest)(nil),  // 2: greet.v1.SayStreamHelloRequest
	(*SayStreamHelloResponse)(nil), // 3: greet.v1.SayStreamHelloResponse
}
var file_greet_v1_service_proto_depIdxs = []int32{
	0, // 0: greet.v1.GreeterService.SayHello:input_type -> greet.v1.SayHelloRequest
	2, // 1: greet.v1.GreeterService.SayStreamHello:input_type -> greet.v1.SayStreamHelloRequest
	1, // 2: greet.v1.GreeterService.SayHello:output_type -> greet.v1.SayHelloResponse
	3, // 3: greet.v1.GreeterService.SayStreamHello:output_type -> greet.v1.SayStreamHelloResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_greet_v1_service_proto_init() }
func file_greet_v1_service_proto_init() {
	if File_greet_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greet_v1_service_proto_rawDesc), len(file_greet_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greet_v1_service_proto_goTypes,
		DependencyIndexes: file_greet_v1_service_proto_depIdxs,
		MessageInfos:      file_greet_v1_service_proto_msgTypes,
	}.Build()
	File_greet_v1_service_proto = out.File
	file_greet_v1_service_proto_goTypes = nil
	file_greet_v1_service_proto_depIdxs = nil
}
