package hmac

import (
	"github.com/alexfalkowski/go-service/v2/crypto/rand"
	"github.com/alexfalkowski/go-service/v2/errors"
)

// NewGenerator constructs a Generator that produces HMAC secret material.
//
// The provided generator is used as the cryptographically-secure randomness source.
func NewGenerator(generator *rand.Generator) *Generator {
	return &Generator{generator: generator}
}

// Generator generates secret strings suitable for use as HMAC key material.
type Generator struct {
	generator *rand.Generator
}

// Generate returns a new HMAC secret string.
//
// The returned string is 32 characters long and is generated by the shared crypto/rand generator.
// If generation fails, the returned error is prefixed with "hmac".
func (g *Generator) Generate() (string, error) {
	t, err := g.generator.GenerateText(32)
	return t, g.prefix(err)
}

func (g *Generator) prefix(err error) error {
	return errors.Prefix("hmac", err)
}
