package hooks

import (
	"github.com/alexfalkowski/go-service/v2/bytes"
	"github.com/alexfalkowski/go-service/v2/crypto/rand"
	"github.com/alexfalkowski/go-service/v2/encoding/base64"
	"github.com/alexfalkowski/go-service/v2/os"
	hooks "github.com/standard-webhooks/standard-webhooks/libraries/go"
)

// NewGenerator constructs a Generator for creating Standard Webhooks secrets.
//
// The returned Generator uses a cryptographically-secure random generator.
func NewGenerator(gen *rand.Generator) *Generator {
	return &Generator{gen: gen}
}

// Generator generates secret values suitable for Standard Webhooks.
type Generator struct {
	gen *rand.Generator
}

// Generate returns a new base64-encoded secret string.
//
// It generates 32 random bytes and encodes them using standard base64.
// The returned string is suitable for use as Config.Secret (as a literal value).
func (g *Generator) Generate() (string, error) {
	b, err := g.gen.GenerateBytes(32)
	return base64.Encode(b), err
}

// NewHook constructs a Standard Webhooks webhook instance from cfg.
//
// Disabled behavior: if cfg is nil/disabled, NewHook returns (nil, nil).
//
// Enabled behavior: NewHook resolves the configured secret using Config.GetSecret and constructs a
// Standard Webhooks Webhook instance using that secret.
//
// Secret encoding expectations:
// The secret bytes are converted to a string and passed to the Standard Webhooks library. In typical
// setups this string is the base64-encoded secret generated by (*Generator).Generate, but NewHook does
// not enforce a particular encoding beyond what the downstream library expects.
func NewHook(fs *os.FS, cfg *Config) (*hooks.Webhook, error) {
	if !cfg.IsEnabled() {
		return nil, nil
	}

	b, err := cfg.GetSecret(fs)
	if err != nil {
		return nil, err
	}

	return hooks.NewWebhook(bytes.String(b))
}
