package hooks

import (
	"maps"
	"strconv"

	"github.com/alexfalkowski/go-service/v2/bytes"
	"github.com/alexfalkowski/go-service/v2/crypto/rand"
	"github.com/alexfalkowski/go-service/v2/encoding/base64"
	"github.com/alexfalkowski/go-service/v2/errors"
	"github.com/alexfalkowski/go-service/v2/net/http"
	"github.com/alexfalkowski/go-service/v2/os"
	"github.com/alexfalkowski/go-service/v2/slices"
	"github.com/alexfalkowski/go-service/v2/time"
	webhooks "github.com/standard-webhooks/standard-webhooks/libraries/go"
)

// ErrEmptySecret indicates that webhook secret configuration resolved to empty bytes.
var ErrEmptySecret = errors.New("hooks: empty secret")

// ErrInvalidConfig indicates webhook secret rotation configuration is incomplete.
var ErrInvalidConfig = errors.New("hooks: invalid config")

// NewGenerator constructs a Generator for creating Standard Webhooks secrets.
//
// The returned Generator uses a cryptographically-secure random generator.
func NewGenerator(gen *rand.Generator) *Generator {
	return &Generator{gen: gen}
}

// Generator generates secret values suitable for Standard Webhooks.
type Generator struct {
	gen *rand.Generator
}

// Generate returns a new base64-encoded Standard Webhooks secret string.
//
// It generates 32 random bytes and encodes them using standard base64. The returned string can be used
// as a literal value in [Config.Secrets]. If the underlying random generator fails, Generate returns
// that error.
func (g *Generator) Generate() (string, error) {
	b, err := g.gen.GenerateBytes(32)
	return base64.Encode(b), err
}

// Hook signs and verifies Standard Webhooks signatures.
//
// A Hook has one active signer and one or more trusted verifiers. This supports
// secret rotation by signing with the active configured secret while accepting
// signatures from the full configured secret set.
type Hook struct {
	signer    *webhooks.Webhook
	verifiers []*webhooks.Webhook
	leeway    time.Duration
}

// Sign computes a Standard Webhooks signature with the active secret.
func (h *Hook) Sign(id string, timestamp time.Time, payload []byte) (string, error) {
	return h.signer.Sign(id, timestamp, payload)
}

// Verify verifies payload and headers against the configured trusted secrets.
//
// When [Config.Leeway] is zero, the Webhook-Timestamp freshness check uses the
// Standard Webhooks library's fixed 5-minute window. When [Config.Leeway] is
// non-zero, Verify checks Webhook-Timestamp against that configured window
// itself, then verifies the signature ignoring the library's own timestamp check.
func (h *Hook) Verify(payload []byte, headers http.Header) error {
	if h.leeway != 0 {
		if err := verifyTimestamp(headers, h.leeway); err != nil {
			return err
		}
	}

	// Standard Webhooks signs the message id, timestamp, and payload, but it does
	// not include a signing key id. During rotation we therefore verify against the
	// configured trusted secrets in order and accept the first match.
	err := ErrInvalidConfig
	for _, verifier := range h.verifiers {
		if verifyErr := h.verifySignature(verifier, payload, headers); verifyErr != nil {
			err = verifyErr
		} else {
			return nil
		}
	}

	return err
}

func (h *Hook) verifySignature(verifier *webhooks.Webhook, payload []byte, headers http.Header) error {
	if h.leeway != 0 {
		return verifier.VerifyIgnoringTimestamp(payload, headers)
	}

	return verifier.Verify(payload, headers)
}

// verifyTimestamp checks the Webhook-Timestamp header against a configured leeway window.
//
// A missing or unparsable header is left for the downstream Standard Webhooks verifier to reject with its
// own required/invalid header error, so this check only reports freshness failures.
func verifyTimestamp(headers http.Header, leeway time.Duration) error {
	ts, ok := parseWebhookTimestamp(headers)
	if !ok {
		return nil
	}

	now := time.Now()

	if now.Sub(ts) > leeway.Duration() {
		return webhooks.ErrMessageTooOld
	}

	if ts.After(now.Add(leeway.Duration())) {
		return webhooks.ErrMessageTooNew
	}

	return nil
}

func parseWebhookTimestamp(headers http.Header) (time.Time, bool) {
	sec, err := strconv.ParseInt(headers.Get(webhooks.HeaderWebhookTimestamp), 10, 64)
	if err != nil {
		return time.Time{}, false
	}

	return time.Unix(sec), true
}

// NewHook constructs a Standard Webhooks hook from cfg.
//
// Disabled behavior: if cfg is nil/disabled, [NewHook] returns (nil, nil).
//
// Enabled behavior: [NewHook] resolves [Config.Secrets] and constructs Standard Webhooks instances
// using those secrets. Source-resolution errors and Standard Webhooks constructor errors are returned
// to the caller.
//
// Secret encoding expectations:
// The secret bytes are converted to a string and passed to the Standard Webhooks library. In typical
// setups this string is the base64-encoded secret generated by [Generator.Generate], with or without the
// Standard Webhooks `whsec_` prefix, but [NewHook] does not enforce a particular encoding beyond what
// the downstream library expects. Empty resolved secrets are rejected with [ErrEmptySecret].
func NewHook(fs *os.FS, cfg *Config) (*Hook, error) {
	if !cfg.IsEnabled() {
		return nil, nil
	}

	return newRotatingHook(fs, cfg)
}

func newRotatingHook(fs *os.FS, cfg *Config) (*Hook, error) {
	if _, ok := cfg.Secrets[cfg.Key]; !ok {
		return nil, ErrInvalidConfig
	}

	active := cfg.Secrets.Get(cfg.Key)

	signer, err := newWebhook(fs, active)
	if err != nil {
		return nil, err
	}

	ids := slices.Collect(maps.Keys(cfg.Secrets))
	slices.Sort(ids)

	verifiers := []*webhooks.Webhook{signer}
	for _, id := range ids {
		if id == cfg.Key {
			continue
		}

		verifier, err := newWebhook(fs, cfg.Secrets[id])
		if err != nil {
			return nil, err
		}
		verifiers = append(verifiers, verifier)
	}

	return &Hook{signer: signer, verifiers: verifiers, leeway: cfg.Leeway}, nil
}

func newWebhook(fs *os.FS, secret string) (*webhooks.Webhook, error) {
	b, err := fs.ReadSource(secret)
	if err != nil {
		return nil, err
	}
	if len(b) == 0 {
		return nil, ErrEmptySecret
	}

	return webhooks.NewWebhook(bytes.String(b))
}
