package hooks

import (
	"github.com/alexfalkowski/go-service/v2/bytes"
	"github.com/alexfalkowski/go-service/v2/crypto/rand"
	"github.com/alexfalkowski/go-service/v2/encoding/base64"
	"github.com/alexfalkowski/go-service/v2/errors"
	"github.com/alexfalkowski/go-service/v2/os"
	hooks "github.com/standard-webhooks/standard-webhooks/libraries/go"
)

// ErrEmptySecret indicates that webhook secret configuration resolved to empty bytes.
var ErrEmptySecret = errors.New("hooks: empty secret")

// NewGenerator constructs a Generator for creating Standard Webhooks secrets.
//
// The returned Generator uses a cryptographically-secure random generator.
func NewGenerator(gen *rand.Generator) *Generator {
	return &Generator{gen: gen}
}

// Generator generates secret values suitable for Standard Webhooks.
type Generator struct {
	gen *rand.Generator
}

// Generate returns a new base64-encoded Standard Webhooks secret string.
//
// It generates 32 random bytes and encodes them using standard base64. The returned string is accepted
// by [NewHook] as a literal [Config.Secret] value. If the underlying random generator fails, Generate
// returns that error.
func (g *Generator) Generate() (string, error) {
	b, err := g.gen.GenerateBytes(32)
	return base64.Encode(b), err
}

// NewHook constructs a Standard Webhooks webhook instance from cfg.
//
// Disabled behavior: if cfg is nil/disabled, [NewHook] returns (nil, nil).
//
// Enabled behavior: [NewHook] resolves the configured secret using [Config.GetSecret] and constructs a
// Standard Webhooks Webhook instance using that secret. Source-resolution errors and Standard Webhooks
// constructor errors are returned to the caller.
//
// Secret encoding expectations:
// The secret bytes are converted to a string and passed to the Standard Webhooks library. In typical
// setups this string is the base64-encoded secret generated by [Generator.Generate], with or without the
// Standard Webhooks `whsec_` prefix, but [NewHook] does not enforce a particular encoding beyond what
// the downstream library expects. Empty resolved secrets are rejected with [ErrEmptySecret].
func NewHook(fs *os.FS, cfg *Config) (*hooks.Webhook, error) {
	if !cfg.IsEnabled() {
		return nil, nil
	}

	b, err := cfg.GetSecret(fs)
	if err != nil {
		return nil, err
	}
	if len(b) == 0 {
		return nil, ErrEmptySecret
	}

	return hooks.NewWebhook(bytes.String(b))
}
