#!/usr/bin/env bash

set -e

# Generate for testing.
protoc -I pkg/grpc/internal --go_out=pkg/grpc/internal --go_opt=paths=source_relative \
    --go-grpc_out=pkg/grpc/internal --go-grpc_opt=paths=source_relative \
    pkg/grpc/internal/greet.proto
