// Package rsa provides RSA key loading, encryption, and decryption helpers for go-service.
//
// This package supports loading RSA keys from PEM-encoded PKCS#1 formats:
//
//   - public key: PEM block "RSA PUBLIC KEY" containing PKCS#1-encoded bytes ([crypto/x509.ParsePKCS1PublicKey])
//   - private key: PEM block "RSA PRIVATE KEY" containing PKCS#1-encoded bytes ([crypto/x509.ParsePKCS1PrivateKey])
//
// It also provides Encryptor/Decryptor helpers that use RSA-OAEP with SHA-512
// and a nil label. Configured keys must use a modulus of at least KeySize bits.
// RSA-OAEP is suitable only for small payloads; with the default 4096-bit keys
// generated by this package, plaintext must be no larger than 382 bytes.
//
// Configuration values are typically loaded using the go-service "source string" pattern (for example "env:NAME",
// "file:/path", or a literal PEM value) via crypto/pem.Decoder.
package rsa
